apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: project1
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-openshift
  type: ClusterIP
